# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x0bgrpc_server\"\'\n\x07Message\x12\r\n\x05token\x18\x01 \x01(\t\x12\r\n\x05roles\x18\x02 \x03(\t\"8\n\x11HasAccessResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x12\n\nhas_access\x18\x02 \x01(\x08\x32K\n\x04\x41uth\x12\x43\n\tHasAccess\x12\x14.grpc_server.Message\x1a\x1e.grpc_server.HasAccessResponse\"\x00\x62\x06proto3')



_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
_HASACCESSRESPONSE = DESCRIPTOR.message_types_by_name['HasAccessResponse']
Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:grpc_server.Message)
  })
_sym_db.RegisterMessage(Message)

HasAccessResponse = _reflection.GeneratedProtocolMessageType('HasAccessResponse', (_message.Message,), {
  'DESCRIPTOR' : _HASACCESSRESPONSE,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:grpc_server.HasAccessResponse)
  })
_sym_db.RegisterMessage(HasAccessResponse)

_AUTH = DESCRIPTOR.services_by_name['Auth']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=27
  _MESSAGE._serialized_end=66
  _HASACCESSRESPONSE._serialized_start=68
  _HASACCESSRESPONSE._serialized_end=124
  _AUTH._serialized_start=126
  _AUTH._serialized_end=201
# @@protoc_insertion_point(module_scope)
