version: '3'
services:
  auth:
    container_name: auth
    build:
      context: .
      dockerfile: auth/Dockerfile
      target: tests
    ports:
      - '5000:5000'
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      POSTGRES_URL: ${POSTGRES_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXP_ACCESS: ${JWT_EXP_ACCESS}
      JWT_EXP_REFRESH: ${JWT_EXP_REFRESH}
    entrypoint: >
      sh -c "python3 -m pytest api/v1 -vv"
    depends_on:
      - redis
      - postgres

  postgres:
    container_name: postgres
    image: postgres:13
    ports:
      - '5234'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - '6379'
